### ISSUE TITLE
Background command triggered by help exits debug/browser

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#1081]
The async operations breaks me out of a debugger session.

```r
> somefunc <- function() { browser(); 1; }
> somefunc()
Called from: somefunc()
Browse[1]> debug at #1: [1] 1
Browse[2]> ?mean           # ess-command: Timeout during background ESS command ’.ess.getHelpAliases()’

> 
```

Versions:

```
ess-version: 18.10.3snapshot [elpa: 20201222.1348] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20201222.1348/)
Mark set [2 times]
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
```

Perhaps the use of async operations should be real-time opt-in/opt-out? Async in general is making it fairly difficult to use the current version of ESS: it's difficult to read help docs (`?funcname`, wait for timeout, type `?funcname` again and maybe see it), and some help impossible to read (`??funcname` will timeout and there is no apparent way to get it).

**Comment by lionel-** [comment]
I think you mean background operations? These are synchronous, not asynchronous, which is why they block the Emacs UI if they take too long.

> Perhaps the use of async operations should be real-time opt-in/opt-out?

I don't think we can do this because they happen all the time, for example as you move the cursor inside functions (eldoc for arguments in the echo area) or as you type (company completions). The user is not supposed to notice these background operations.

I have merged #1080 which should help a bit, can you try it out please? It seems that we'll need to increase the timeout for aliases retrieval since it takes such a long time on some platforms. What timeout do you think would work for you?

**Comment by lionel-** [comment]
Thinking more about this, we could just bump the timeout to infinity for this particular command.

**Comment by lionel-** [comment]
@r2evans We now restart browser sessions on interrupts and timeouts. I have also bumped this particular timeout to 30 seconds. Thank you for all this testing and reporting!

**Comment by r2evans** [comment]
My apologies for confounding async/background ... 

After upgrading to `ess-20201229.923` (and exiting/restarting emacs), even though the time-to-fail has changed, it still fails:

```r
> ?ls
                  ### 6 seconds going through 'Retrieving RDS aliases...'
                  # ess-command: Timeout during background ESS command ’.ess.getHelpAliases()’
> ?ls
                  # works
```

On a similar note, `??` still fails in 1 second (not 6), likely for the same reason. Further frustrating (for me) is that while a second `?ls` (if paused a moment) *will work*, yet `??ls` will never work. I can use `help.search(.)`, so it isn't unavailable, but the ESSR's power is unavailable.

(I really hate that emacs and ESS are so problematic on windows ...)

Some options, if any of them appeal to you:

1. Is there a clean debugging method with elips that I can do? I'm very comfortable with R debugging (though I've never `debug(.ess*)` functions), and I understand elisp to a certain degree, I do not know how to debug elisp at all.
2. Since I cannot send you a computer with windows and emacs installed to test it, I could start a webex with you and let you control *this* emacs, in case you think it would be faster and worth your time. I know that troubleshooting-via-comment can be difficult. I also know your time is valuable and split among many projects, let me know if there's something more I can do to help.

---

Actually ... this version looks like it does *not* have 8ce7cb8b7c854156785a3e345b01d919d35fba57 and 40f9581243063176acc020a0bc6fdfeae1595d86, so I'll put those in manually ...

Unfortunately, it still fails in the same way.

**Comment by lionel-** [comment]
I could reproduce the `??ls` timeout and have pushed a quick fix: https://github.com/emacs-ess/ESS/commit/b91585db

I also found the explanation for the mystery of the persisting timeout. The signature of `ess-command` is so complicated that I messed up the argument position 😓. We should switch to keyword arguments at some point. I have fixed this and reduced the timeout for the aliases to its previous value: https://github.com/emacs-ess/ESS/commit/484b20aa.

Hopefully that should sort things out.

**Comment by r2evans** [comment]
Okay, that fixes both `?ls` and `??ls`. Thanks!

**Comment by lionel-** [comment]
Great! Please let me know of any other process issues you might encounter. Happy holidays!

**Comment by r2evans** [comment]
(Just my suggested patch in https://github.com/emacs-ess/ESS/issues/1025#issuecomment-752155492, all else is smoothing out again.)

Happy holidays!
