### ISSUE TITLE
ess 20180629.212 is broken : doesn't start.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [emacs-ess/ESS#596]
I follow a few MELPA packages via via `emacs`'s package panager (i.e. in my directory, thus shadowing systemwide packages installed via Debian packages), among which `ess`. A recent update broke it.

Starting `ess` (M-x R) from a "virgin" `emacs` session fails with the following message : 
```
ess-r-s-define-runners: Symbol’s function definition is void: ess-s-define-runners
```

Removing MELPA's `ess` (thus relying on systemwide ess package as packaged in Debian testing, which is currently at 17.11-2), allows to start `ess`.

Let me know what further information you might need.

**Comment by vspinu** [comment]
It was a big change to make the whole ESS autoloaded  and looks like this one is not loaded when needed. Fixed in master should propagate to melpa within an hour or so.

@jabranham I now wonder why do we define S runners in R-mode. I think we should move that into sp6 mode and get rid of those ugly ess-r-s-define-xyz.

**Comment by EmmanuelCharpentier** [comment]
Le dimanche 01 juillet 2018 à 01:04 -0700, Vitalie Spinu a écrit :
> It was a big change to make the whole ESS autoloaded  and looks like
> this one is not loaded when needed. Fixed in master should propagate
> to melpa within an hour or so.

Thanks. I'll retry it in a while (but not "in an hour or so" : I have
to work on something else *now*...) and keep you posted if necessary.
--Emmanuel Charpentier

**Comment by jabranham** [comment]
@vspinu yeah, I noticed that when trying to obsolete these languages (#595). I'm working on splitting it up so that all the S stuff is in the S files and the R stuff in the R files.

**Comment by EmmanuelCharpentier** [comment]
FYI, as of Jul 2, 2018 13:10:06 (UTC+0200), melpa still proposes 20180629.212 (which is still broken ;-)...

**Comment by jabranham** [comment]
@EmmanuelCharpentier - MELPA is serving 20180701.100. You may need to `package-refresh-contents` to see it.

**Comment by EmmanuelCharpentier** [comment]
> @EmmanuelCharpentier - MELPA is serving 20180701.100. You may need to package-refresh-contents to see it.

Heh, I did that (and the "Manage emacs packages" menu entry does that too...). Time of propagation to melpa (mirrors ?) ?

Anyway, I just got (and tested) `20180701.100` ... and got the same error. Again, removing it (thus enabling the systemwide `ess`) fixed the problem.

**Comment by jabranham** [comment]
@EmmanuelCharpentier Huh, that's surprising, and I can't reproduce it. Are you sure Emacs isn't loading old bytecode or something?

**Comment by EmmanuelCharpentier** [comment]
> @EmmanuelCharpentier Huh, that's surprising, and I can't reproduce it. Are you sure Emacs isn't loading old bytecode or something?

I just reproduced  that on another machine (the one I used yesterday), that had had this problem and was fixed by removing melpa's ess (through the "Manage emacs packages" menu entry), thus enabling a systemwide installation of ess : 
* system's ess : R starts, restart emacs : R starts correctly.
* restart emacs, install melpas'ess : R doesn't start (same error as before
* uninstall melpa's ess, restart emacs : R starts.

Do you need other tests ? Other information ?

**Comment by vspinu** [comment]
I don't see how this could be happening. There is only one place where `ess-s-define-runners` is used and that place is protected with `(require 'ess-sp6-d)` where this function lives. So it must be your local issue; old bytecode as @jabranham said.

**Comment by vspinu** [comment]
Actually now I see. I just tried it myself and got similar error but with a different function. You should delete ess folder from your ELPA, then restart emacs and only then install. Issues are likely to occur if install happens from the same session where old ESS is loaded.

**Comment by EmmanuelCharpentier** [comment]
I told you that I restarted emacs every time... Isn't that a problem with the package management code ?

Anyway, the version available this morning (20180702.1407) seems to fix the R startup problem.
