### ISSUE TITLE
Highlighting disappears in iESS buffer

### ISSUE THREAD

**Issue by prosoitos** [emacs-ess/ESS#705]
Starting yesterday, after an update of ess through melpa (though there may be no link with this), I started having highlighting issues in my iESS buffer. Something that had never happened to me previously. A new melpa update today did not change things.

**Problem:**
When I launch an R process, or when I send a command to it, the normal highlighting in the iESS buffer appears for an instant, then most of it disappears (a couple of elements, always the same ones, remain highlighted).
If I run `M-x inferior-ess-mode`, even those remaining bits of highlighting disappear.

Highlighting is normal in the ESS buffer.

**System info:**
OS: 4.18.11-arch1-1-ARCH
Emacs: 26.1-2
ESS: 20181003.2153

I would appreciate any advice. Thank you!!!

**Comment by jabranham** [comment]
Thanks for the report, it should be fixed whenever MELPA next builds ESS.

**Comment by prosoitos** [comment]
Great! Thanks!

**Comment by prosoitos** [comment]
Just noticed another syntax highlighting issue (let me know if you would rather I open a different issue since this may be totally unrelated):

**Comment by lionel-** [comment]
can you try again with current master?

`%op%` should normally not be highlighted at all in the iESS buffer because `%` is a common output character and would throw off highlighting.

**Comment by prosoitos** [comment]
Sorry @lionel- for not getting back to you sooner on this.

With the current Melpa version, I still do not have highlighting in the ESS buffer (while I used to until a recent update), but in the iESS buffer, the `>` is now highlighted as an operator and the `%`s are not highlighted (which might be the normal behaviour: I don't recall how it was until I lost the highlighting in the ESS buffer).

If your question is still relevant, I will download the current master and see whether I get a different result (please let me know since I have neglected to get back to you for so long. Thank you!).

**Comment by lionel-** [comment]
Hmm, this sounds like the behaviour you would get with an older revision. Could you make sure you have the most recent one please?

**Comment by prosoitos** [comment]
Something even more bizarre is going on with my iESS highlighting:

The highlighting does not disappear within seconds as it used to when I first opened this issue, *except* in some rare cases. For instance, if I create an object `a` of class "Corpus" with the package "tm" and run `str(a)` from the ESS buffer, the highlighting appears briefly, then disappears. But if I run `str(a)` directly in the iESS buffer, the highlighting does not break.

If I run `str()` on other objects from the ESS buffer, nothing breaks...

**Comment by lionel-** [comment]
What highlighting?

**Comment by prosoitos** [comment]
> What highlighting?

`texts` is my Corpus object.

`str(texts)` run from the ESS buffer.

![2018-10-15_10-18](https://user-images.githubusercontent.com/4634851/46966791-92523180-d063-11e8-8fcb-5f5c64e40cb8.png)

`str(texts)` run directly from iESS (in the first case, this is how it shows up for an instant before turning into the above picture).

![2018-10-15_10-19](https://user-images.githubusercontent.com/4634851/46966829-ab5ae280-d063-11e8-8441-b5e3b47fc1db.png)

**Comment by prosoitos** [comment]
> You're right, these issues seem to be linked to quotes.

Yes: it looks like the 2nd quote isn't detected anymore...

**Comment by mmaechler** [comment]
I've seen similar behavior (relatively rarely) in the `*R*` (iESS) buffer.  Note Marie-Helene that in both of your screenshots (thanks a lot for those!) there is some correct highlighting:  The first one *does* nicely using the "string" fontification for the `$content` list elements and the `class` attributes where as the 2nd one (you prefer) no longer does any string fontification.  So *both* fontifications are wrong to some extent.

I also agree with @prosoitos that this is relatively recent behavior.. (couple of weeks?) and I had hoped was just transient and we would go back to normal "magically" when the fontification keywords/engines were cleaned up.

**Comment by lionel-** [comment]
I don't think there is any new behaviour concerning string fontification. But maybe the work in the comint filter causes the highlighting to be applied on a smaller window of output than before? cc @vspinu

**Comment by mmaechler** [comment]
Thanks @lionel-  Looking at my own "changes", it could've been the switch from Emacs 25 to Emacs 26 which was simultaneous with the OS upgrade (from Fedora 26 to 28).
I've found at least one E26 bug (or a bug in the interaction with GNOME...)that wasn't there in E25: In `ediff`, the tiny ediff control window ('frame'  in emacs speak)) does not get focus for me and I need to use the mouse which is pain with my use habits.   
So it could be a comint bug in E26 not present in E25

**Comment by lionel-** [comment]
I have the same issue with ediff :/ So that's not a WM thing.

**Comment by vspinu** [comment]
The fact that font-lock runs twice is a bad sign but there have been any direct changes to this functionality for many months, even years I would say. 

@jabranham I don't think we should define `comint-highlight-promt` variable. It's not our namespace.

**Comment by jabranham** [comment]
We've defined `comint-highlight-prompt` for a while. I removed it in 7fe56f96d1f09535d9376868f2ed774ff148142c (for precisely the reason you mention) but added it back quickly in 82173c5812b996448dc7b7f6e359cf6a1ba11e4e because I forgot that our font-lock system somehow relies on the value of the symbol to be the name of the face.

**Comment by vspinu** [comment]
>  forgot that our font-lock system somehow relies on the value of the symbol to be the name of the face.

Yeh, this should be fixed then instead. I bet we use `comint-highligh-prompt` only in a place or two.

**Comment by jabranham** [comment]
> Yeh, this should be fixed then instead

I agree and have been meaning to look at it but haven't found time yet. Too late to make such a change for 18.10 anyway.

>  I bet we use comint-highligh-prompt only in a place or two.

Right, and I tried to eliminate it with #706 but then we'd possibly have different colored prompts,  as you pointed out.

**Comment by prosoitos** [comment]
@lionel- 

> Note that there was a bug which caused %op% to be highlighted no matter what, which is why you might now see it disabled if you have an old customisation that disabled it silently for a while.

:smile: Yup, that was it :slightly_smiling_face: I did not have `ess-R-fl-keyword:%op%` in my alist for `ess-R-font-lock-keywords` and I never thought of checking this since I did not change anything on my end and it never crossed my mind that there could have been a bug creating highlighting that I never set for myself :smile: 

Thank you very much!

**Comment by prosoitos** [comment]
Apologies for having yet another question about highlighting:

My `*` are not highlighted anymore (neither in ESS nor in iESS buffers). I could be wrong, but I think that I remember it being highlighted like the other operators before I opened this issue. All other operators are highlighted fine.

**Comment by lionel-** [comment]
@prosoitos Confirmed thanks, I'll take a look.

**Comment by prosoitos** [comment]
OK. Thank you @lionel- for looking into it. I really thought that `*` was highlighted before, but I couldn't remember for sure. If this is not the result of a new bug and has never been implemented, it is obviously not critical.
