### ISSUE TITLE
Help frame split with `ess-help-own-frame`

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#826]
From the ESS mailing list:

```

>> On Wed, Jan 23 2019 14:20, Henric Winell via ESS-help wrote:

> Hi,

> There's something strange going on with the R help buffers.  I'm using the
> latest ess-20190122.2108 from melpa, but it's not particular to that version:

> I want each help buffer to appear in its own separate frame, and have

>  '(ess-help-own-frame t)
>  '(ess-help-reuse-window nil)

> in my .emacs.  Now, pressing, say, '?lm' in an R buffer opens up the help page
> in a separate frame as it should.  However, using 'l' to execute the code in the
> 'Examples:' section results in the help frame being split up with the help
> buffer on top and the R buffer below. Then, pressing 'q' or 'k' should bury or
> remove the help frame, respectively, but it's still visible and has the help
> buffer on top replaced by the R buffer.

> Henric Winell
```

Related #823 #816

**Comment by jabranham** [comment]
This should have been fixed in be0850b23128508e33f0b0a58376660d6ef3e493

**Comment by vspinu** [comment]
Indeed. Your emails are not getting through. You can see that in the [archive](https://stat.ethz.ch/pipermail/ess-help/2019-January/thread.html)

**Comment by henwin** [comment]
Thanks for looking into this! Unfortunately, there are still remaining issues:

- Pressing 'l' now _almost_ works. The frame is no longer split, but focus shifts from the help frame to the R buffer. The help frame used to stay active, making it easy to execute line-by-line and see what happens at each step.
- Pressing 'q' or 'k' is still broken. Instead of burying or killing the help frame and switching back to the R buffer, the R buffer is now shown in the still active help frame.
- Also, I've now noticed that executing, say, `?lm` twice results in two help frames. Previously, if a help frame already existed for an object it just switched to that frame.

BTW, my `display-buffer-alist` is `nil`.
