### ISSUE TITLE
Flymake warning

### ISSUE THREAD

**Issue by miguelmorin** [emacs-ess/ESS#883]
I install ESS following [these directions](https://emacs.stackexchange.com/questions/48341/unable-to-install-ess-package), adding these to `~/.emacs`:

    (require 'package)
    (add-to-list 'package-archives
                 '("melpa-stable" . "https://stable.melpa.org/packages/"))
    (add-to-list 'package-archives
                 '("melpa" . "http://melpa.org/packages/"))
    (package-initialize)

then typing `M-x package-install RET ess RET`, and adding this to `~/.emacs` as well:

    (require 'ess-site)

Now when I open an R file in Emacs, I get this message in a buffer:

    Warning (flymake): Disabling backend ess-r-flymake because (error Cannot find program ’R’)
    Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
    Warning (flymake): Disabling backend ess-r-flymake because (error Cannot find program ’R’)
    Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)

and typing in the buffer with the R file is slower because of warnings from `Flymake`.

I have also set the inferior R program as in [this thread](https://emacs.stackexchange.com/questions/42537/ess-r-error-searching-for-program):

    (setq inferior-ess-r-program "R")

The result is the same. Running `M-: RET (executable-find "R")` displays `"/usr/local/bin/R"` in the mini-buffer.

The setup worked fine with ESS installed from source and appeared when I switched to ESS from MELPA.

I asked on [emacs.stackexchange.com](https://emacs.stackexchange.com/questions/48509/ess-installation-does-not-initialize-flymake) and one person suggested adding it here.

**Comment by jabranham** [comment]
I don't understand how flymake can't find R but `(executable-find "R")` returns an R binary.

I'm also not sure how flymake could be responsible for slow typing. Since the backend got disabled, it shouldn't affect much. Can you try disabling flymake (with, e.g. M-x flymake-mode after visiting an R buffer) and see if that solves your issue?

**Comment by jabranham** [comment]
Closing this since we didn't hear back from the author

**Comment by miguelmorin** [comment]
@jabranham Sorry for the slow reply, I got a deluge of emails and deadlines.

## Slow typing

I cannot reproduce the slow typing problem.

## `No such file` warning

Upon opening an R buffer today, I got this message:

```
Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning [ess-r-flymake  *ess-r-flymake*]:  Error in cat("@@warning: @@", e) : 
  argument 2 (type ’list’) cannot be handled by ’cat’
Calls: esslint ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous> -> cat
In addition: Warning messages:
1: In dir.create(path) :
  cannot create dir ’~/.R/lintr_cache’, reason ’No such file or directory’
2: In gzfile(file, "wb") :
  cannot open compressed file ’~/.R/lintr_cache/b7893f32377841e47553cfd37cd6f9fc39954681’, probable reason ’No such file or directory’
Execution halted

Warning [ess-r-flymake  *ess-r-flymake*-759805]:  Error in cat("@@warning: @@", e) : 
  argument 2 (type ’list’) cannot be handled by ’cat’
Calls: esslint ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous> -> cat
In addition: Warning messages:
1: In dir.create(path) :
  cannot create dir ’~/.R/lintr_cache’, reason ’No such file or directory’
2: In gzfile(file, "wb") :
  cannot open compressed file ’~/.R/lintr_cache/a982077a3d8054f2c4b33ad6d52351ef46021951’, probable reason ’No such file or directory’
Execution halted
```

It was right that `~/.R` did not exist and I created it. The warnings disappeared

## R executable

I confirm that `flymake` can now find the `R` executable. The line `(setq inferior-ess-r-program "/usr/local/bin/R")` was the problem: without the line, I `(executable-find "R")` returns `nil` and I get this warning twice:

```
Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
```

I added that line to my `~/.emacs` on March 26, so I don't understand why the changes did not take effect 4 days after, even though I turn off the computer every day.

##

Now I get only this message:

```
Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning (flymake): Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
```

I found that [I could disable the legacy stuff](http://emacs.1067599.n8.nabble.com/Disable-flymake-log-about-proc-legacy-flymake-td454765.html) with 

```
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

So, although the last one is quick-and-dirty, it works for me.

**Comment by vspinu** [comment]
> Warning [ess-r-flymake  *ess-r-flymake*]:  Error in cat("@@warning: @@", e) : 

Where is this one coming from? We don't have this cat call in the repo. 

> So, although the last one is quick-and-dirty, it works for me.

This "legacy" stuff is a pain in the rear. I have disabled it too due to errors in some other contexts.

**Comment by mmaechler** [comment]
> slow typing
I do occasionally observe "almost lockup" almost surely related to ESS (using R).
Could it be that flymake needs time in large `*.R` files or when the `*R*` buffer is large?
In such cases ... (more than once a week), I do use the [Flymake] menu to turn it off and that does help.

**Comment by miguelmorin** [comment]
@vspinu I don't know where the warning comes from. I checked that I have the latest package with `M-x list-packages` and `U`, which gave `No packages available to upgrade` in the mini-buffer. Flymake has version 1.0.6. I removed `-/.R` to cause the warning again, but it did not come. Do you have suggestions to track this down?

**Comment by jabranham** [comment]
There seems to be some weirdness in lintr somewhere, see https://github.com/jimhester/lintr/issues/308. For now if you create `~/.R/lintr_cache/` it should solve the issue.

> I do occasionally observe "almost lockup" almost surely related to ESS (using R). Could it be that flymake needs time in large *.R files or when the *R* buffer is large? In such cases ... (more than once a week), I do use the [Flymake] menu to turn it off and that does help.

@mmaechler Yes, it's possible that flymake slows down Emacs in large buffers.

>> Warning [ess-r-flymake ess-r-flymake]: Error in cat("@@warning: @@", e)

> Where is this one coming from? We don't have this cat call in the repo.

That's `ess-r--flymake-def-linter` unless I'm mistaken

> This "legacy" stuff is a pain in the rear. I have disabled it too due to errors in some other contexts.

@vspinu What error does it cause? It should just (silently) fail, log to the flymake-log buffer, then never start it again.

**Comment by mhofert** [comment]
I observe (and then do) exactly the same as Martin Maechler (and it's really getting annoying; creating `~/.R/lintr_cache` didn't have any effect). 

I also see `error in process sentinel: not enough arguments for format string` (disappearing after disabling flymake) and there is one more person who did the same, see [here](https://emacs.stackexchange.com/questions/50692/error-in-process-sentinel-not-enough-arguments-for-format-string-with-simple). The link refers to this page here, which is how I found this discussion.

**Comment by apparluk** [comment]
Emacs 26.3
ESS melpa/melpa-stable

_cf_: https://github.com/emacs-ess/ESS/issues/883#issuecomment-491856361

Disabling the legacy stuff or setting ess-use-flymake to nil in init.el still results in the cited **&ast;Flymake log&ast;** output.

```elisp
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

```elisp
'(ess-use-flymake nil)
```

**&ast;Flymake log&ast;**

```elisp
Warning [flymake myfile.R]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
```

**Comment by jsilve24** [comment]
I ran into the same problem.. @mhofert solutin worked for me (adding ~/.R/lintr_cache)  this is weird.

**Comment by teotenn** [comment]
Can somebody help me to solve the problem? I was having the same problems described here. The one about not finding the init file was solved using `(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)` in my emacs init file. But I still receive the following message:

```
Warning [ess-r-flymake  *ess-r-flymake*]:  Error in cat("@@warning: @@", e) : 
  argument 2 (type ’list’) cannot be handled by ’cat’
Calls: esslint ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous> -> cat
In addition: Warning message:
In file(con, "r") :
  cannot open file ’x <- data.frame(x=1:10, y=letters[1:10])’: Invalid argument
Execution halted
 Disable showing Disable logging
```

The part of `cannot open file` is always the first line of the R script I try to check. I have this one set for test, but I tried opening other scripts and the only difference is that one line.

What is even more weird is that, in my linux laptop I can use flymake with ess without problems, but this problem appears on windows only. I have the same version of flymake in both (1.2.2) and same Emacs and ESS too.

I also tryied creating the `~/R/lintr_cache` but nothing changes. Here is my config file.

```
(setq tt/lintr-linters
      "lintr::linters_with_defaults(
         line_length_linter = line_length_linter(120)
       )"
 )

(use-package flymake
  :if (eq system-type 'windows-nt)
  :config
  (remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake))

(use-package ess
  :if (eq system-type 'windows-nt)
  :init
  (setq inferior-ess-r-program "C:/Users/teodorm3/Bin/R-4.2.1/bin/R.exe"))

(use-package ess
  :init
  (setq ess-style 'RStudio)
  :config
  (setq ess-r-flymake-linters tt/lintr-linters)
  (setq ess-eval-visibly-p t) ; ESS process (print all)
  (setq ess-ask-for-ess-directory nil)
  ;; R console hook
  (defun my-inferior-ess-init ()
    (setq-local ansi-color-for-comint-mode 'filter)
    (define-key inferior-ess-mode-map [\C-up]
      'comint-previous-matching-input-from-input)
    (define-key inferior-ess-mode-map [\C-down]
      'comint-next-matching-input-from-input)
    (define-key inferior-ess-mode-map [\C-x \t]
      'comint-dynamic-complete-filename))
  (add-hook 'inferior-ess-mode-hook 'my-inferior-ess-init)
  ;; Syntax highlight
  (setq ess-R-font-lock-keywords
      '((ess-R-fl-keyword:keywords . t)
	(ess-R-fl-keyword:constants . t)
	(ess-R-fl-keyword:modifiers . t)
	(ess-R-fl-keyword:fun-defs . t)
	(ess-R-fl-keyword:assign-ops . t)
	(ess-R-fl-keyword:%op% . t)
	(ess-fl-keyword:fun-calls . t)
	(ess-fl-keyword:numbers . t)
	(ess-fl-keyword:operators)
	(ess-fl-keyword:delimiters)
	(ess-fl-keyword:=)
	(ess-R-fl-keyword:F&T . t)))
  )
```
